// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    LootCategories: typeof import('./components/loot/LootCategories.vue')['default']
    LootList: typeof import('./components/loot/LootList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TRCBack: typeof import('./components/TRCBack.vue')['default']
    TRCDamageRelations: typeof import('./components/TRCDamageRelations.vue')['default']
    TRCMenu: typeof import('./components/TRCMenu.vue')['default']
    TRCPokemon: typeof import('./components/TRCPokemon.vue')['default']
    TRCRaidDetail: typeof import('./components/TRCRaidDetail.vue')['default']
    TRCSelect: typeof import('./components/TRCSelect.vue')['default']
  }
}
